# Generated by Django 4.2.30 on 2026-10-02 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggreement', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('NIN', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='/static/images/blankPerson.jpeg', upload_to='images/')),
                ('chair', models.CharField(default='Not Added', max_length=20)),
                ('chairTel', models.CharField(default='Not Added', max_length=20)),
                ('nextOfKin', models.CharField(default='Not Added', max_length=20)),
                ('nextOfKinTel', models.CharField(default='Not Added', max_length=20)),
                ('buz', models.CharField(default='Not Added', max_length=20)),
                ('buzloc', models.CharField(default='Not Added', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='/static/images/logo-placeholder.png', upload_to='images/')),
                ('co_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('subscription', models.BooleanField(default=False)),
                ('expiry', models.DateField(default=datetime.date(2026, 10, 16))),
                ('subscription_status', models.CharField(default='Trial', max_length=10)),
                ('time_left', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_Date', models.DateField(auto_now_add=True)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('processing_fee', models.IntegerField()),
                ('total_amm', models.DecimalField(decimal_places=6, max_digits=18)),
                ('duration', models.IntegerField()),
                ('last_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=6, max_digits=18)),
                ('comments', models.TextField(default='Not Added')),
                ('startDate', models.DateField(auto_now_add=True)),
                ('penalty', models.IntegerField(default=0)),
                ('effectDay', models.IntegerField(default=0)),
                ('dailyPay', models.IntegerField(default=0)),
                ('penaltyAmountAdded', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower')),
                ('lender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amm', models.DecimalField(decimal_places=6, default=0.0, max_digits=16)),
                ('txnID', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.IntegerField(default=0)),
                ('percentage_paid', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('bal', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('time_left', models.IntegerField()),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower')),
                ('lender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender')),
                ('loan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='Not Added', max_length=100)),
                ('description', models.TextField(default='Not Added')),
                ('proof', models.ImageField(null=True, upload_to='images/')),
                ('asset_photo', models.ImageField(null=True, upload_to='images/')),
                ('aggr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.aggreements')),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower')),
                ('lender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender')),
                ('loan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='lender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender'),
        ),
        migrations.AddField(
            model_name='aggreements',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower'),
        ),
        migrations.AddField(
            model_name='aggreements',
            name='lender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender'),
        ),
        migrations.AddField(
            model_name='aggreements',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans'),
        ),
    ]
